### ISSUE TITLE
Bug in Readme?

### ISSUE THREAD

**Issue by Datamance** [Jesse-jApps/django-altair#2]
```       
     context['chart2'] = alt.Chart(source).mark_circle().encode(
```

 ... Shouldn't `chart2` just be chart? Or alternatively, 

``` {% load django_altair %}
<div>
    {% render_chart chart %}
</div>
``` 

^^^^ `chart` would have to be `chart2`.

**Comment by Jesse-jApps** [comment]
Thanks. Corrected in https://github.com/Jesse-jApps/django-altair/commit/439c08910f835332f2277d20fd09e2347b69d876
