### ISSUE TITLE
No module named 'django_altair'

### ISSUE THREAD

**Issue by lmielke** [Jesse-jApps/django-altair#3]
First, great idea!
Unfortunately its not working for me. 
Maybe its just me not understanding, but I am a bit confused about both "django_altair" and the "render_chart" tag. I tried two approaches:

1. If I run manage.py runserver on your example, as expected I get: 
    No module named 'django_altair'. since the app does not exist nor does any import with that name. Is there some install I missed?

2. Also, I took your sample coding and included it into an existing django app (my_django_altair), but when I run it, I get: 
  a)  if I run it as in your docs: No module named 'my_django_altair'...
  b) if I leave "django_altair" out, I get: Invalid block tag on line 18: 'render_chart', expected 'endblock'. Did you forget to register or load this tag?

**Note:** I can see all three js-sripts being properly imported. Also when I run context['chart'].serve() inside views.py then its showing me the chart. So the chart object itself seems to be intact. Also in views.py I am not using a TemplateView, but a generic DetailView, but I assume, this has no impact.
pls advice and thanks

**Comment by Datamance** [comment]
You probably need to `pip install` the library.

**Comment by Jesse-jApps** [comment]
Sorry @lmielke for the late reply. @Datamance is right. You need to first install the library using pip.
```
pip3 install .
```
from within to root-folder.
Updated readme in https://github.com/Jesse-jApps/django-altair/commit/2ff6d920f6c99ef49f12d649f5cab4b0abf6a9cf
